In [1]:
import pandas as pd

X_train = pd.read_csv('../data/processed/X_train.csv')
X_val = pd.read_csv('../data/processed/X_val.csv')
X_test = pd.read_csv('../data/processed/X_test.csv')

y_train = pd.read_csv('../data/processed/y_train.csv').squeeze()
y_val = pd.read_csv('../data/processed/y_val.csv').squeeze()
y_test = pd.read_csv('../data/processed/y_test.csv').squeeze()

In [2]:
late_cols = ['NumberOfTime30-59DaysPastDueNotWorse',
             'NumberOfTime60-89DaysPastDueNotWorse',
             'NumberOfTimes90DaysLate']

X_train['TotalTimesLate'] = X_train[late_cols].sum(axis=1)
X_val['TotalTimesLate']   = X_val[late_cols].sum(axis=1)
X_test['TotalTimesLate']  = X_test[late_cols].sum(axis=1)

X_train[['NumberOfTime30-59DaysPastDueNotWorse',
         'NumberOfTime60-89DaysPastDueNotWorse',
         'NumberOfTimes90DaysLate', 'TotalTimesLate']].head()

,NumberOfTime30-59DaysPastDueNotWorse,NumberOfTime60-89DaysPastDueNotWorse,NumberOfTimes90DaysLate,TotalTimesLate
0,0,0,0,0
1,0,0,0,0
2,0,0,0,0
3,0,0,0,0
4,0,0,0,0

In [3]:
X_train['TotalTimesLate'].describe()

count    104818.000000
mean          0.402211
std           1.102173
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          18.000000
Name: TotalTimesLate, dtype: float64

In [4]:
# Does this new feature separate defaulters from non-defaulters?
combined = pd.concat([X_train['TotalTimesLate'], y_train], axis=1)
combined.groupby('SeriousDlqin2yrs')['TotalTimesLate'].mean()

SeriousDlqin2yrs
0    0.28701
1    2.03223
Name: TotalTimesLate, dtype: float64

In [5]:
X_train['IncomePerDependent'] = X_train['MonthlyIncome'] / (X_train['NumberOfDependents'] + 1)
X_val['IncomePerDependent']   = X_val['MonthlyIncome'] / (X_val['NumberOfDependents'] + 1)
X_test['IncomePerDependent']  = X_test['MonthlyIncome'] / (X_test['NumberOfDependents'] + 1)

X_train[['MonthlyIncome', 'NumberOfDependents', 'IncomePerDependent']].head()

   MonthlyIncome  NumberOfDependents  IncomePerDependent
0         5163.0                 0.0              5163.0
1         2800.0                 1.0              1400.0
2         3333.0                 0.0              3333.0
3        15161.0                 0.0             15161.0
4         6500.0                 1.0              3250.0

In [6]:
X_train['IncomePerDependent'].describe()

count    1.048180e+05
mean     4.561001e+03
std      7.844361e+03
min      0.000000e+00
25%      2.149625e+03
50%      4.000000e+03
75%      5.392000e+03
max      1.794060e+06
Name: IncomePerDependent, dtype: float64

In [7]:
combined = pd.concat([X_train['IncomePerDependent'], y_train], axis=1)
combined.groupby('SeriousDlqin2yrs')['IncomePerDependent'].mean()

SeriousDlqin2yrs
0    4616.052628
1    3782.053737
Name: IncomePerDependent, dtype: float64

In [8]:
X_train['AgeGroup'] = pd.cut(X_train['age'], bins=[0, 30, 45, 60, 110], 
                                labels=['<30', '30-45', '45-60', '60+'])
X_val['AgeGroup']   = pd.cut(X_val['age'], bins=[0, 30, 45, 60, 110], 
                                labels=['<30', '30-45', '45-60', '60+'])
X_test['AgeGroup']  = pd.cut(X_test['age'], bins=[0, 30, 45, 60, 110], 
                                labels=['<30', '30-45', '45-60', '60+'])

X_train['AgeGroup'].value_counts()

AgeGroup
45-60    37561
60+      31462
30-45    28343
<30       7452
Name: count, dtype: int64

In [9]:
combined = pd.concat([X_train['AgeGroup'], y_train], axis=1)
combined.groupby('AgeGroup', observed=True)['SeriousDlqin2yrs'].mean()

AgeGroup
<30      0.108696
30-45    0.091628
45-60    0.067623
60+      0.030894
Name: SeriousDlqin2yrs, dtype: float64

In [10]:
# One-hot encode the AgeGroup feature
X_train = pd.get_dummies(X_train, columns=['AgeGroup'], drop_first=True)
X_val   = pd.get_dummies(X_val, columns=['AgeGroup'], drop_first=True)
X_test  = pd.get_dummies(X_test, columns=['AgeGroup'], drop_first=True)

In [11]:
# Save the feature engineered datasets
X_train.to_csv('../data/processed/X_train_fe.csv', index=False)
X_val.to_csv('../data/processed/X_val_fe.csv', index=False)
X_test.to_csv('../data/processed/X_test_fe.csv', index=False)

In [12]:
X_train.columns.tolist()

['RevolvingUtilizationOfUnsecuredLines',
 'age',
 'NumberOfTime30-59DaysPastDueNotWorse',
 'DebtRatio',
 'MonthlyIncome',
 'NumberOfOpenCreditLinesAndLoans',
 'NumberOfTimes90DaysLate',
 'NumberRealEstateLoansOrLines',
 'NumberOfTime60-89DaysPastDueNotWorse',
 'NumberOfDependents',
 'TotalTimesLate',
 'IncomePerDependent',
 'AgeGroup_30-45',
 'AgeGroup_45-60',
 'AgeGroup_60+']

In [13]:
X_train.shape, X_val.shape, X_test.shape

((104818, 15), (22453, 15), (22459, 15))

In [14]:
X_train.to_csv('../data/processed/X_train_fe.csv', index=False)
X_val.to_csv('../data/processed/X_val_fe.csv', index=False)
X_test.to_csv('../data/processed/X_test_fe.csv', index=False)